library(shiny)
library(lubridate)

shinyUI(
    fluidPage(
        titlePanel('Inputs en Shiny'),
        tabsetPanel(tabPanel('Inputs',
                             
                             sidebarLayout(sidebarPanel(
                                 sliderInput('Slider_Input',
                                             'Number of bins:',
                                             value = 50,
                                             min = 0,
                                             max = 100,
                                             step = 10,
                                             post = '%',
                                             animate = TRUE),
                                 sliderInput('Slider_Input_Range',
                                             'Select Range:',
                                             value = c(0, 200),
                                             min = 0,
                                             max = 200,
                                             step = 10,
                                             animate = TRUE),
                                 selectInput('Select_Input',
                                             'Choose a car:',
                                             choices = rownames(mtcars),
                                             selected = 'Honda Civic',
                                             multiple = FALSE),
                                 selectizeInput('Select_Input2',
                                             'Choose cars:',
                                             choices = rownames(mtcars),
                                             selected = 'Honda Civic',
                                             multiple = TRUE),
                                 dateInput('Date_Input',
                                           'Set a Date:',
                                           value = today(),
                                           min = today() - 60,
                                           max = today() + 60,
                                           language = 'es',
                                           weekstart = 1),
                                 dateRangeInput('Date_Input_Range',
                                           'Set Dates:',
                                           start = today()-14,
                                           end = today(),
                                           separator = 'a',
                                           weekstart = 0),
                                 numericInput('Numeric_Input',
                                              'Enter a Number:',
                                              value = 1,
                                              min = 0,
                                              max = 100,
                                              step = 1),
                                 checkboxInput('Checkbox_Input',
                                              'Select If True:',
                                              value = 0),
                                 checkboxGroupInput('Groupbox',
                                               'Select Options:',
                                               choices = LETTERS[1:10]),
                                 radioButtons('Radio_Button',
                                              'Choose Sex:',
                                              choices = c('Male', 'Female')),
                                 textInput('Text_Input',
                                           'Enter Text:'),
                                 textAreaInput('Text_Area',
                                           'Enter Paragraph:'),
                                 actionButton('Action_Button',
                                               'Ok'),
                                 actionLink('Action_Link',
                                               'Next'),
                                 passwordInput('Pass_Input',
                                               'Enter Password:',
                                               value = ''),
                                 submitButton(text = 'Reprocess')
                             ),
                             
                             mainPanel(
                                 h2('Slider Input Simple'),
                                 verbatimTextOutput('slider1'),
                                 h2('Slider Input with Range'),
                                 verbatimTextOutput('slider2'),
                                 h2('Select Input'),
                                 verbatimTextOutput('select1'),
                                 h2('Select Input Multiple'),
                                 verbatimTextOutput('select2'),
                                 h2('Select Date'),
                                 verbatimTextOutput('date1'),
                                 h2('Select Range Date'),
                                 verbatimTextOutput('date2'),
                                 h2('Numeric Input'),
                                 verbatimTextOutput('numeric'),
                                 h2('Checkbox Simple'),
                                 verbatimTextOutput('checkbox1'),
                                 h2('Group Checkbox'),
                                 verbatimTextOutput('checkbox2'),
                                 h2('Radio Buttons'),
                                 verbatimTextOutput('radio'),
                                 h2('Text Input'),
                                 verbatimTextOutput('text1'),
                                 h2('Paragraph Input'),
                                 verbatimTextOutput('text2'),
                                 h2('Action Button'),
                                 verbatimTextOutput('button'),
                                 h2('Action Link'),
                                 verbatimTextOutput('link'),
                                 h2('Password Input'),
                                 verbatimTextOutput('pass')
                                 
                             )
                             )
                             )
                    )
        )
    )